# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: lexical-analyzer.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: lexical-analyzer
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: lexical-analyzer

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lexical-analyzer-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
